# Generated by Django 6.1.1 on 2026-09-28 08:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('publication_index', models.CharField(max_length=20, unique=True, verbose_name='Индекс издания')),
                ('editor_last_name', models.CharField(max_length=100, verbose_name='Фамилия редактора')),
                ('editor_first_name', models.CharField(max_length=100, verbose_name='Имя редактора')),
                ('editor_patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество редактора')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена экземпляра')),
            ],
        ),
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Номер')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='PrintingHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('is_active', models.BooleanField(default=True, verbose_name='Работает')),
            ],
        ),
        migrations.CreateModel(
            name='PrintRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circulation', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Тираж')),
                ('newspaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_runs', to='newspapers.newspaper', verbose_name='Газета')),
                ('printing_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_runs', to='newspapers.printinghouse', verbose_name='Типография')),
            ],
        ),
        migrations.AddField(
            model_name='newspaper',
            name='printing_houses',
            field=models.ManyToManyField(related_name='newspapers', through='newspapers.PrintRun', to='newspapers.printinghouse', verbose_name='Типографии'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('post_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='newspapers.postoffice', verbose_name='Почтовое отделение')),
                ('print_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='newspapers.printrun', verbose_name='Тираж')),
            ],
        ),
        migrations.AddConstraint(
            model_name='printrun',
            constraint=models.UniqueConstraint(fields=('printing_house', 'newspaper'), name='unique_print_run'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(fields=('print_run', 'post_office'), name='unique_delivery'),
        ),
    ]
